output: ./docs
pipeline:
  install:
    - npm --version
    - node --version
    - npm install
  lint:
    - npm run lint
  build:
    - npm run coverage
  test:
    - npm test
  docs:
    - npm run generate-docs
